### PR TITLE
Serialization fix

### PR DESCRIPTION
**Pull request by philosoralphter**

### CODE REVIEW

**Comment by philosoralphter** [comment]
Hold on  a second on this I pushed one commit early.

**Comment by philosoralphter** [comment]
Here it is @hankim813.  Looks like another commit came in on master so you may have to rebase...

**Comment by hankim813** [comment]
@philosoralphter do you mind pulling the updated master and rebasing? :pray:

**Comment by philosoralphter** [comment]
sure!  I'll do that tonight and let you know!

**Comment by hankim813** [comment]
@philosoralphter yup this is the general rebase flow we use:

```
$ git add .
$ git commit -m "msg"
$ git checkout master
$ git fetch origin master
$ git rebase origin/master
$ git checkout <feature branch>
$ git rebase -i master
$ git push origin <feature branch>
```

**Comment by philosoralphter** [comment]
Alright @hankim813. Rebased.

**Comment by hankim813** [comment]
@philosoralphter just deployed this. Thanks so much! can you also make a PR for the client side as well? https://github.com/segment-integrations/analytics.js-integration-woopra/blob/master/lib/index.js#L109-L115

I believe we are using out old stringification

**Comment by philosoralphter** [comment]
Yeah, @hankim813  I noticed that last night.  I will do so.  Thanks for the great work on this. I'm glad to have this issue finally sorted out

**Pull request merged**
