### PR TITLE
Update parameter name for tracking event name and add context object

### PR DESCRIPTION
**Pull request by billyvg**
* Update `ce_name` parameter to `event`
* Serializes the `context`/`options` object and sends it as `context` for tracking and identify requests

### CODE REVIEW

**Comment by billyvg** [comment]
We realized we may run into potential issues with the length of the GET request, I'm guessing we can change the request type to a POST in `request()`?

**Comment by lambtron** [comment]
Thanks @billyvg, our team to review shortly.

**Comment by sperand-io** [comment]
@billyvg indeed, that's exactly right. if your API accepts POSTs we can definitely make that change. Want to open a separate pr for that?

**Comment by billyvg** [comment]
Yeah I'll open a new PR for that

**Comment by sperand-io** [comment]
hey @billyvg we can get this out on Thursday, pending a better understanding of why you need to attach the entire stringified `context` object, rather than just using the fields pulled out automatically already (user-agent, ip, etc). If you need to access other fields in that dictionary, you can pull them out and attach them to specific fields.

Let us know! Other than that, looks good.

**Comment by billyvg** [comment]
We'd prefer having a catchall approach to `context` and having our services
decide which ones to use.  That way if there are updates we don't have to
change our integration.

**Pull request merged**
